AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Spaced Repetition App

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs18.x
    MemorySize: 256

Resources:
  SpacedRepTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SpacedRepetition
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  DecksBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: spaced-rep-decks

  ReviewFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers/review.handler
      Environment:
        Variables:
          TABLE_NAME: SpacedRepetition
          BUCKET_NAME: spaced-rep-decks
      Events:
        ApiReview:
          Type: HttpApi
          Properties:
            Path: /review
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - handlers/review.ts

  JoinDeckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers/joinDeck.handler
      Environment:
        Variables:
          TABLE_NAME: SpacedRepetition
          BUCKET_NAME: spaced-rep-decks
      Events:
        ApiJoinDeck:
          Type: HttpApi
          Properties:
            Path: /join-deck
            Method: POST

Outputs:
  ApiEndpoint:
    Description: "HTTP API endpoint"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
